### PR TITLE
Port to webextensions

### PR DESCRIPTION
**Pull request by francov**
Obviously it is a complete rewrite, so you need to add the addon ID in the manifest (...i  think) and the yandex api key in the background script file. Let me know if it is ok
I have to try the webextensions-polyfill in order to port this extension on Chrome store too.

### CODE REVIEW

**Comment by francov** [comment]
Ah, this fix issue #3 too

**Comment by francov** [comment]
Just realized 2 things, in the `manifest.json`:

1. there is a typo in the name `"name": "hot-translate2"`: I added the `2` in the name for test purposes
2. the section related to the application->gecko->id:
  ```
  "applications": {
      "gecko": {
        "id": "xxxxxxxxxxxxxxxxxxxxx"
      }
    }
  ```
is commented out because the id must contains the `@` character, probably an email address will suffice.

**Comment by francov** [comment]
This commit makes the addon cross browser compatible with the use of `webextensions-polyfill.js` library

**Comment by RealFatCat** [comment]
Hi.
This project is abandoned.
I think it will better if you 'fork' this project and keep it alive with this code you send me.
Thanks.

**Comment by francov** [comment]
OK! Thank you for the notification.

**Pull request closed without merging**
